### ISSUE TITLE
Add github action for releasing

### ISSUE THREAD

**Issue by sjsrey** [pysal/libpysal#298] opened 2020-06-28 19:26 UTC
Follow example from [mapclassify](https://github.com/pysal/mapclassify/blob/master/.github/workflows/release.yml)

**Comment by jGaboardi** [comment] 2020-07-07 16:20
This issue is a duplicate of #279.

**Comment by jGaboardi** [comment] 2020-07-07 17:30
Addressing in #316

**Closed** 2020-08-14 22:18 UTC
Labels: duplicate, environment/install
