### ISSUE TITLE
regression in libpysal.io.fileio.FileIO

### ISSUE THREAD

**Issue by jGaboardi** [pysal/libpysal#624] opened 2023-11-02 12:45 UTC
#620 [introduced a regression](https://github.com/pysal/libpysal/pull/620/files#diff-63caaa2e22b46da7ffb19263d6483704698216a98ab2ec087ea6ba01f19f9ea1L93) (for example [in `spaghetti`](https://github.com/pysal/spaghetti/actions/runs/6726774671/job/18283603971#step:7:296)), however, I'm not sure if it's something we should fix in `libpysal` or in affected downstream packages. The change was prompted by `ruff` whereby:

```python
return open(dataPath, mode)
``` 

was replaced by:

```python
with open(dataPath, mode) as file:
    return file
```

for proper context handling.

This broke no tests in `libpysal` and so far I can only find that it has broken tests in `spaghetti`.

**Comment by martinfleis** [comment] 2023-11-02 12:49
I was wondering about this change while reviewing but since there was no error in CI I assumed it works and my Python knowledge is limited regarding this behaviour. 

It is a regression that should be fixed here. I would simply revert the change and add global `noqa` to affected files.

**Closed** 2023-11-02 14:08 UTC
Labels: bug
