### ISSUE TITLE
Creating Weights  from dataframe: IndexError: index 0 is out of bounds for axis 0 with size 0

### ISSUE THREAD

**Issue by raholler** [pysal/libpysal#479] opened 2022-10-16 18:38 UTC
I get the following error when running 
```python
W = libpysal.weights.KNN.from_dataframe(df,  k=4)
```

```
File Anaconda3\envs\geo_new\lib\site-packages\libpysal\weights\distance.py:905, in DistanceBand.from_dataframe(cls, df, threshold, geom_col, ids, **kwargs)
    903 if geom_col is None:
    904     geom_col = df.geometry.name
--> 905 pts = get_points_array(df[geom_col])
    906 if ids is None:
    907     ids = df.index.tolist()

File Anaconda3\envs\geo_new\lib\site-packages\libpysal\weights\util.py:1081, in get_points_array(iterable)
   1078 try:
   1079     if HAS_SHAPELY:
   1080         data = np.vstack(
-> 1081             [
   1082                 np.array(shape.centroid.coords)[0]
   1083                 if isinstance(shape, BaseGeometry)
   1084                 else np.array(shape.centroid)
   1085                 for shape in first_choice
   1086             ]
...
   1092                 for shape in first_choice
   1093             ]
   1094         )

IndexError: index 0 is out of bounds for axis 0 with size
```
The error disappears, when I restrict the geodataframe to areas without islands.

- Platform information: nt win32
- Python version: 3.10.6
- SciPy version: 1.9.1
- NumPy version: 1.23.2
- Geopandas: 0.11.1
- libpysal: 4.6.2

[test.zip](https://github.com/pysal/libpysal/files/9795414/test.zip)

**Comment by sjsrey** [comment] 2022-10-27 16:38
@raholler could you share the example data so we can check into this?

**Comment by sjsrey** [comment] 2022-10-27 17:10
The issue seems to be that there are observations that do not have geometries:

![image](https://user-images.githubusercontent.com/118042/198354780-bad8d171-b3d0-4d8a-ab9b-96f5ca962c9c.png)

Without coordinates, it isn't possible to calculate the distances needed for the knn determination.
If you drop those observations, all is well.

**Comment by sjsrey** [comment] 2022-10-27 17:12
There are 11 such observations:

![image](https://user-images.githubusercontent.com/118042/198355351-db6101c7-ad69-4604-96b8-fac5550dbf19.png)

**Comment by raholler** [comment] 2022-10-28 07:00
Thanks for the swift response. I am sorry, I actually checked in the originial data 
```python
data.query("geometry.isnull()")
```
and it seemed that there were no missing geometries. I will check again, what is going on.

**Comment by sjsrey** [comment] 2022-10-29 16:35
Closing since the problem is not due to a bug.

**Closed by sjsrey** 2022-10-29 16:35 UTC
